-- Better window navigation -- option key -> M
-- vim.keymap.set('n', '<M-H>', '<C-w>h')
-- vim.keymap.set('n', '<M-J>', '<C-w>j')
-- vim.keymap.set('n', '<M-K>', '<C-w>k')
-- vim.keymap.set('n', '<M-L>', '<C-w>l')
-- vim.keymap.set('n', '<M-,>', '10<C-w>>')
-- vim.keymap.set('n', '<M-.>', '10<C-w><')
-- vim.keymap.set('n', '<M-]>', '5<C-w>-')
-- vim.keymap.set('n', '<M-\\>', '5<C-w>+')
